name: cupertino_back_gesture
description: A package to set custom width of iOS back swipe gesture area.
version: 0.0.3
homepage: https://github.com/PiN73/cupertino_back_gesture

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
